rules:
  # https://github.com/textlint-rule/textlint-rule-no-todo
  no-todo: true
  # https://github.com/sapegin/textlint-rule-terminology
  terminology:
    defaultTerms: true
    terms:
      - DoiT
      - Doit International
